# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FastKernelDensityAnalysisDialog
                                 A QGIS plugin
 A fast kernel density visualization plugin for geospatial analytics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-10
        copyright            : (C) 2023 by Bojian Zhu
        email                : bjzhu999@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FastKernelDensityAnalysis class from file FastKernelDensityAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fast_kernel_density_analysis import FastKernelDensityAnalysis
    return FastKernelDensityAnalysis(iface)
