# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FastKernelDensityAnalysisDialog
                                 A QGIS plugin
 A fast kernel density visualization plugin for geospatial analytics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-10
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Bojian Zhu
        email                : bjzhu999@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'fast_kernel_density_analysis_dialog_base.ui'))


class FastKernelDensityAnalysisDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(FastKernelDensityAnalysisDialog, self).__init__(parent)
        os.environ['QT_AUTO_SCREEN_SCALE_FACTOR'] = '1'  # Fix screen size disparity
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        lyr = self.mcb.currentLayer()
        self.fcbLat.setLayer(lyr)
        self.fcbLon.setLayer(lyr)
        self.fcbTime.setLayer(lyr)

